services:
  api:
   image: dimejii/back:latest
   networks:
      - dimejiinet

  frontend:
    image: dimejii/front:latest
    ports:
      - "3000:80"
    depends_on:
      - api
    restart: always
    networks:
      - dimejiinet


networks:
  dimejiinet:

